/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturas.app.views;

import facturas.app.Controller;
import facturas.app.models.Ticket;
import facturas.app.utils.FormatUtils;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agustin
 */
public class FiltersView extends javax.swing.JFrame {

    /**
     * Creates new form FiltersView
     * @param controller
     * @param ticketsTable
     */
    public FiltersView(Controller controller, JTable ticketsTable) {
        this.controller = controller;
        this.ticketsTable = ticketsTable;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minTotalAmountTextField = new javax.swing.JTextField();
        maxTotalAmountTextField = new javax.swing.JTextField();
        minIvaTextField = new javax.swing.JTextField();
        maxIvaTextField = new javax.swing.JTextField();
        cuitTextField = new javax.swing.JTextField();
        minDateLabel = new javax.swing.JLabel();
        maxDateLabel = new javax.swing.JLabel();
        minTotalAmountLabel = new javax.swing.JLabel();
        maxTotalAmountLabel = new javax.swing.JLabel();
        minIvaLabel = new javax.swing.JLabel();
        maxIvaLabel = new javax.swing.JLabel();
        cuitLabel = new javax.swing.JLabel();
        appyFilters = new javax.swing.JButton();
        ticketTypesScrollPane = new javax.swing.JScrollPane();
        ticketTypesList = new javax.swing.JList<>();
        minDateChooser = new com.toedter.calendar.JDateChooser();
        maxDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FILTROS");
        setLocation(new java.awt.Point(0, 350));

        minDateLabel.setText("Fecha Minino");

        maxDateLabel.setText("Fecha Maxima");

        minTotalAmountLabel.setText("Importe Total Min.");

        maxTotalAmountLabel.setText("Importe Total Max.");

        minIvaLabel.setText("IVA Minimo");

        maxIvaLabel.setText("IVA Maximo");

        cuitLabel.setText("CUIT");

        appyFilters.setText("Aplicar filtros");
        appyFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appyFiltersActionPerformed(evt);
            }
        });

        ticketTypesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "6 - Factura B", "1 - Factura A", "11 - Factura C", "3 - Nota de Crédito A", "2 - Nota de Débito A", "13 - Nota de Crédito C" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ticketTypesScrollPane.setViewportView(ticketTypesList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(appyFilters)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(minTotalAmountLabel)
                                    .addComponent(minIvaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuitLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(minTotalAmountTextField)
                                    .addComponent(minIvaTextField)
                                    .addComponent(cuitTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(minDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(minDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxTotalAmountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maxIvaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxTotalAmountTextField)
                            .addComponent(maxIvaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(ticketTypesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maxDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minDateLabel)
                        .addComponent(maxDateLabel))
                    .addComponent(maxDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minTotalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxTotalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minTotalAmountLabel)
                    .addComponent(maxTotalAmountLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minIvaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxIvaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minIvaLabel)
                    .addComponent(maxIvaLabel))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuitLabel))
                        .addGap(46, 46, 46)
                        .addComponent(appyFilters))
                    .addComponent(ticketTypesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appyFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appyFiltersActionPerformed
        // TODO add your handling code here:
        //ticketTypesScrollPane.setViewportView(ticketsTable);
        Map<String, Object> selectedFilters = getFilters();
        List<Ticket> tickets = controller.getTickets(selectedFilters);
        
        DefaultTableModel model = (DefaultTableModel)ticketsTable.getModel();
        cleanTable(model);
        for (Ticket t : tickets) {
            model.addRow(FormatUtils.ticketToForm(t));
        }
    }//GEN-LAST:event_appyFiltersActionPerformed

    public Map<String, Object> getFilters() {
        Map<String, Object> selectedFilters = new HashMap<> ();
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        selectedFilters.put("startDate", sdf.format(minDateChooser.getDate()));
        selectedFilters.put("finishDate", sdf.format(maxDateChooser.getDate()));
        selectedFilters.put("minTotal", minTotalAmountTextField.getText());
        selectedFilters.put("maxTotal", maxTotalAmountTextField.getText());
        selectedFilters.put("minIva", minIvaTextField.getText());
        selectedFilters.put("maxIva", maxIvaTextField.getText());
        selectedFilters.put("companyCuit", cuitTextField.getText());
        selectedFilters.put("ticketTypesList", ticketTypesList.getSelectedValuesList());
        
        return selectedFilters;
    }
    
    private void cleanTable(DefaultTableModel model) {
        for (int i = model.getRowCount() - 1; 0 <= i; i--)
            model.removeRow(i);
    }
    
    private Controller controller;
    private JTable ticketsTable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appyFilters;
    private javax.swing.JLabel cuitLabel;
    private javax.swing.JTextField cuitTextField;
    private com.toedter.calendar.JDateChooser maxDateChooser;
    private javax.swing.JLabel maxDateLabel;
    private javax.swing.JLabel maxIvaLabel;
    private javax.swing.JTextField maxIvaTextField;
    private javax.swing.JLabel maxTotalAmountLabel;
    private javax.swing.JTextField maxTotalAmountTextField;
    private com.toedter.calendar.JDateChooser minDateChooser;
    private javax.swing.JLabel minDateLabel;
    private javax.swing.JLabel minIvaLabel;
    private javax.swing.JTextField minIvaTextField;
    private javax.swing.JLabel minTotalAmountLabel;
    private javax.swing.JTextField minTotalAmountTextField;
    private javax.swing.JList<String> ticketTypesList;
    private javax.swing.JScrollPane ticketTypesScrollPane;
    // End of variables declaration//GEN-END:variables
}
