/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturas.app.views;

import com.toedter.calendar.JTextFieldDateEditor;
import facturas.app.Controller;
import facturas.app.database.SQLFilter;
import facturas.app.database.SectorDAO;
import facturas.app.models.Provider;
import facturas.app.models.Ticket;
import facturas.app.models.Withholding;
import facturas.app.utils.AutoSuggestor;
import facturas.app.utils.FormatUtils;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agustin
 */
public class FiltersView extends javax.swing.JFrame {

    /**
     * Creates new form FiltersView
     * @param controller
     * @param ticketsTable
     */
    public FiltersView(Controller controller, JTable ticketsTable) {
        this.controller = controller;
        this.ticketsTable = ticketsTable;
        initComponents();
        providersAutoSuggestor = new AutoSuggestor(providersComboBox, getProvidersName());
        providersAutoSuggestor.autoSuggest();
        sectorsAutoSuggestor = new AutoSuggestor(sectorsComboBox, SectorDAO.getSectors());
        sectorsAutoSuggestor.autoSuggest();
    }
    
    public void updateSuggestions() {
        providersAutoSuggestor.setSuggestions(getProvidersName());
        sectorsAutoSuggestor.setSuggestions(SectorDAO.getSectors());
    }
    
    private List<String> getProvidersName() {
        List<String> names = new LinkedList<>();
        for (Provider p : controller.getProviders()) {
            names.add(p.getValues().get("name"));
        }
        return names;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseNSellButtonGroup = new javax.swing.ButtonGroup();
        withholdingGroupButton = new javax.swing.ButtonGroup();
        minTotalAmountTextField = new javax.swing.JTextField();
        maxTotalAmountTextField = new javax.swing.JTextField();
        minIvaTextField = new javax.swing.JTextField();
        maxIvaTextField = new javax.swing.JTextField();
        minDateLabel = new javax.swing.JLabel();
        maxDateLabel = new javax.swing.JLabel();
        minTotalAmountLabel = new javax.swing.JLabel();
        maxTotalAmountLabel = new javax.swing.JLabel();
        minIvaLabel = new javax.swing.JLabel();
        maxIvaLabel = new javax.swing.JLabel();
        cuitLabel = new javax.swing.JLabel();
        appyFilters = new javax.swing.JButton();
        ticketTypesScrollPane = new javax.swing.JScrollPane();
        ticketTypesList = new javax.swing.JList<>();
        minDateChooser = new com.toedter.calendar.JDateChooser();
        maxDateChooser = new com.toedter.calendar.JDateChooser();
        purchaseRadioButton = new javax.swing.JRadioButton();
        saleRadioButton = new javax.swing.JRadioButton();
        bothRadioButton = new javax.swing.JRadioButton();
        withholdingRadioButton = new javax.swing.JRadioButton();
        ticketRadioButton = new javax.swing.JRadioButton();
        bothRadioButton2 = new javax.swing.JRadioButton();
        providersComboBox = new javax.swing.JComboBox<>();
        sectorsComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noTicketWithholdingTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();

        purchaseNSellButtonGroup.add(purchaseRadioButton);
        purchaseNSellButtonGroup.add(saleRadioButton);
        purchaseNSellButtonGroup.add(bothRadioButton);

        withholdingGroupButton.add(withholdingRadioButton);
        withholdingGroupButton.add(ticketRadioButton);
        withholdingGroupButton.add(bothRadioButton2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FILTROS");
        setLocation(new java.awt.Point(0, 350));

        minDateLabel.setText("Fecha Minino");

        maxDateLabel.setText("Fecha Maxima");

        minTotalAmountLabel.setText("Importe Total Min.");

        maxTotalAmountLabel.setText("Importe Total Max.");

        minIvaLabel.setText("IVA Minimo");

        maxIvaLabel.setText("IVA Maximo");

        cuitLabel.setText("Proveedor");

        appyFilters.setText("Aplicar filtros");
        appyFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appyFiltersActionPerformed(evt);
            }
        });

        ticketTypesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "6 - Factura B", "1 - Factura A", "11 - Factura C", "3 - Nota de Crédito A", "2 - Nota de Débito A", "13 - Nota de Crédito C" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ticketTypesScrollPane.setViewportView(ticketTypesList);

        minDateChooser.setDateFormatString("dd-MM-yyyy");
        JTextFieldDateEditor textField = (JTextFieldDateEditor) minDateChooser.getDateEditor();
        textField.setEditable(false);

        maxDateChooser.setDateFormatString("dd-MM-yyyy");
        textField = (JTextFieldDateEditor) maxDateChooser.getDateEditor();
        textField.setEditable(false);

        purchaseRadioButton.setText("Compras");

        saleRadioButton.setText("Ventas");

        bothRadioButton.setSelected(true);
        bothRadioButton.setText("Ambos");

        withholdingRadioButton.setText("Retenciones");

        ticketRadioButton.setText("Facturas");

        bothRadioButton2.setSelected(true);
        bothRadioButton2.setText("Ambos");

        jLabel1.setText("Rubro");

        jLabel2.setText("Nro. Comprob/Reten");

        jLabel3.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(appyFilters))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(minDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minTotalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(minIvaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cuitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bothRadioButton)
                            .addComponent(saleRadioButton)
                            .addComponent(purchaseRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(minDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(minTotalAmountTextField)
                                .addComponent(minIvaTextField)
                                .addComponent(bothRadioButton2)
                                .addComponent(providersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(withholdingRadioButton)
                            .addComponent(ticketRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noTicketWithholdingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ticketTypesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(maxTotalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maxIvaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maxDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sectorsComboBox, 0, 150, Short.MAX_VALUE)
                            .addComponent(maxDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxTotalAmountTextField)
                            .addComponent(maxIvaTextField)
                            .addComponent(idTextField))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minDateLabel)
                        .addComponent(maxDateLabel))
                    .addComponent(maxDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minTotalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxTotalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minTotalAmountLabel)
                    .addComponent(maxTotalAmountLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minIvaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxIvaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minIvaLabel)
                    .addComponent(maxIvaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuitLabel)
                    .addComponent(providersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sectorsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noTicketWithholdingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseRadioButton)
                            .addComponent(withholdingRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saleRadioButton)
                            .addComponent(ticketRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bothRadioButton)
                            .addComponent(bothRadioButton2))
                        .addGap(35, 35, 35)
                        .addComponent(appyFilters)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ticketTypesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appyFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appyFiltersActionPerformed
        Map<String, Object> selectedFilters = getFilters();
        List<Withholding> tickets = controller.getTickets(selectedFilters);
        tickets.addAll(controller.getWithholdings(selectedFilters));
        
        DefaultTableModel model = (DefaultTableModel)ticketsTable.getModel();
        cleanTable(model);
        for (Withholding t : tickets) {
            if (withholdingRadioButton.isSelected() && !(t instanceof Ticket)) {
                model.addRow(FormatUtils.ticketToForm(t));
            } else if (ticketRadioButton.isSelected() && t instanceof Ticket) {
                model.addRow(FormatUtils.ticketToForm(t));
            } else if (bothRadioButton2.isSelected()) {
                model.addRow(FormatUtils.ticketToForm(t));
            }
        }
    }//GEN-LAST:event_appyFiltersActionPerformed

    public Map<String, Object> getFilters() {
        Map<String, Object> selectedFilters = new HashMap<> ();
        
        selectedFilters.put("id", idTextField.getText());
        selectedFilters.put("number", noTicketWithholdingTextField.getText());
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if(minDateChooser.getDate()!=null) selectedFilters.put("startDate", sdf.format(minDateChooser.getDate())); 
        if(maxDateChooser.getDate()!=null) selectedFilters.put("finishDate", sdf.format(maxDateChooser.getDate()));
        selectedFilters.put("minTotal", minTotalAmountTextField.getText());
        selectedFilters.put("maxTotal", maxTotalAmountTextField.getText());
        selectedFilters.put("minIva", minIvaTextField.getText());
        selectedFilters.put("maxIva", maxIvaTextField.getText());
        
        SQLFilter providersDoc = new SQLFilter();
        providersDoc.add("name", "=", providersAutoSuggestor.getText(), String.class);
        
        selectedFilters.put("providersDocs", getDocsList(controller.getProviders(providersDoc)));
        selectedFilters.put("ticketTypesList", ticketTypesList.getSelectedValuesList());
        selectedFilters.put("purchase", purchaseRadioButton.isSelected());
        selectedFilters.put("sale", saleRadioButton.isSelected());
        selectedFilters.put("sector", sectorsAutoSuggestor.getText());
        
        return selectedFilters;
    }
    
    private List<String> getDocsList(List<Provider> list) {
        List<String> namesList = new LinkedList<>();
        for (Provider p : list) {
            namesList.add(p.getValues().get("docNo"));
        }
        return namesList;
    }
    
    public void updateSectors(List<String> sectors) {
        sectorsAutoSuggestor.setSuggestions(sectors);
    }
    
    public void updateProviders(List<String> names) {
        providersAutoSuggestor.setSuggestions(names);
    }
    
    private void cleanTable(DefaultTableModel model) {
        for (int i = model.getRowCount() - 1; 0 <= i; i--)
            model.removeRow(i);
    }
    
    private Controller controller;
    private JTable ticketsTable;
    private AutoSuggestor providersAutoSuggestor;
    private AutoSuggestor sectorsAutoSuggestor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appyFilters;
    private javax.swing.JRadioButton bothRadioButton;
    private javax.swing.JRadioButton bothRadioButton2;
    private javax.swing.JLabel cuitLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JDateChooser maxDateChooser;
    private javax.swing.JLabel maxDateLabel;
    private javax.swing.JLabel maxIvaLabel;
    private javax.swing.JTextField maxIvaTextField;
    private javax.swing.JLabel maxTotalAmountLabel;
    private javax.swing.JTextField maxTotalAmountTextField;
    private com.toedter.calendar.JDateChooser minDateChooser;
    private javax.swing.JLabel minDateLabel;
    private javax.swing.JLabel minIvaLabel;
    private javax.swing.JTextField minIvaTextField;
    private javax.swing.JLabel minTotalAmountLabel;
    private javax.swing.JTextField minTotalAmountTextField;
    private javax.swing.JTextField noTicketWithholdingTextField;
    private javax.swing.JComboBox<String> providersComboBox;
    private javax.swing.ButtonGroup purchaseNSellButtonGroup;
    private javax.swing.JRadioButton purchaseRadioButton;
    private javax.swing.JRadioButton saleRadioButton;
    private javax.swing.JComboBox<String> sectorsComboBox;
    private javax.swing.JRadioButton ticketRadioButton;
    private javax.swing.JList<String> ticketTypesList;
    private javax.swing.JScrollPane ticketTypesScrollPane;
    private javax.swing.ButtonGroup withholdingGroupButton;
    private javax.swing.JRadioButton withholdingRadioButton;
    // End of variables declaration//GEN-END:variables
}
